version: '3.8'

volumes:
  static_volume:
  postgres_data:
  media_volume:

services:
  db:
    container_name: postgres
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ./.env

  web:
    container_name: foodgram
    image: 'ezrawick/foodgram:latest'
    restart: always
    command: gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.19.6
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - ./nginx/:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - web 

